restore conf

diff --git a/.github/workflows/build-docker-image-rosetta.yaml b/.github/workflows/build-docker-image-rosetta.yaml
--- a/.github/workflows/build-docker-image-rosetta.yaml
+++ b/.github/workflows/build-docker-image-rosetta.yaml
@@ -1,9 +1,12 @@
 name: Build and push rosetta docker image
 
 on:
-  push:
-    branches:
-      - v0.14.1-rosetta
+  workflow_dispatch:
+    inputs:
+      tag:
+        description: Github tag to release binaries for (reusing an existing tag will make the pipeline fail)
+        required: true
+        default: latest
 
 jobs:
   release:
@@ -20,11 +23,17 @@ jobs:
 
     steps:
 
+      - name: Validate tag
+        env:
+          SEMVER: ${{ github.event.inputs.tag }}
+        run: |
+          if [[ $SEMVER =~ v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\-rosetta ]]; then echo "Tag is okay" && exit 0; else echo "invalid tag" && exit 1; fi          
+
       - name: Checkout code
         uses: actions/checkout@v2
         with:
           fetch-depth: '0'
-          ref: v0.14.1-rosetta
+          ref: ${{ github.event.inputs.tag }}
           submodules: recursive
 
       - name: Install Cosign
@@ -47,17 +56,17 @@ jobs:
       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME_ROS }}
-          password: ${{ secrets.DOCKER_HUB_TOKEN_ROS }}
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
-      - name: Build and push docker image for all platforms
+      - name: Build and push docker image 
         run: |
           make build-push-docker-images-rosetta
         env:
-          SEMVER: v0.14.1-rosetta
+          SEMVER: ${{ github.event.inputs.tag }}
 
       - name: Sign the images with GitHub OIDC
         run: cosign sign --oidc-issuer https://token.actions.githubusercontent.com ${TAGS}
         env:
-          TAGS: tototesteur/axelar-core:v0.14.1-rosetta
+          TAGS: axelarnet/axelar-core:${{ github.event.inputs.tag }}-rosetta
           COSIGN_EXPERIMENTAL: 1
