fix: fix build pipelines from fixes from main (#880)
* chore: fix typo in workflow (#749)

* chore: add validation on tags in workflows (#760)

diff --git a/.github/workflows/build-docker-image-and-binaries.yaml b/.github/workflows/build-docker-image-and-binaries.yaml
--- a/.github/workflows/build-docker-image-and-binaries.yaml
+++ b/.github/workflows/build-docker-image-and-binaries.yaml
@@ -17,6 +17,12 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
+      - name: Validate tag
+        env:
+          SEMVER: ${{ github.event.inputs.tag }}
+        run: |
+          if [[ $SEMVER =~ v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then echo "Tag is okay" && exit 0; else echo "invalid tag" && exit 1; fi
+
       - name: Checkout code
         uses: actions/checkout@v2
         with:
@@ -48,11 +54,11 @@ jobs:
         run: |
           make build-push-docker-images
         env:
-          SEMVER: $${{ github.event.inputs.tag }}
+          SEMVER: ${{ github.event.inputs.tag }}
 
       - name: Build Binaries for Linux/MacOS
         env:
-          SEMVER: $${{ github.event.inputs.tag }}
+          SEMVER: ${{ github.event.inputs.tag }}
         run: |
           make build-binaries-in-docker
 
@@ -61,7 +67,7 @@ jobs:
         with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: ./bin/*
-          tag: $${{ github.event.inputs.tag }}
+          tag: ${{ github.event.inputs.tag }}
           overwrite: true
           file_glob: true
 
