improve comment

diff --git a/.github/workflows/build-docker-image-rosetta.yaml b/.github/workflows/build-docker-image-rosetta.yaml
--- a/.github/workflows/build-docker-image-rosetta.yaml
+++ b/.github/workflows/build-docker-image-rosetta.yaml
@@ -27,7 +27,7 @@ jobs:
         env:
           SEMVER: ${{ github.event.inputs.tag }}
         run: |
-          if [[ $SEMVER =~ v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\-rosetta ]]; then echo "Tag is okay" && exit 0; else echo "invalid tag" && exit 1; fi          
+          if [[ $SEMVER =~ v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\-rosetta ]]; then echo "Tag is okay" && exit 0; else echo "invalid tag" && exit 1; fi
 
       - name: Checkout code
         uses: actions/checkout@v2
@@ -59,7 +59,7 @@ jobs:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
-      - name: Build and push docker image 
+      - name: Build and push docker image rosetta
         run: |
           make build-push-docker-images-rosetta
         env:
