test

diff --git a/.github/workflows/packaging.yaml b/.github/workflows/packaging.yaml
--- a/.github/workflows/packaging.yaml
+++ b/.github/workflows/packaging.yaml
@@ -1,4 +1,4 @@
-name: Package linux binaries
+name: Package apt binaries
 
 env:
   VERSIONS_LIST: "0.10.7,0.13.6,0.14.1,0.17.3,0.18.3,0.19.4,0.21.1,0.24.0,0.26.5,0.28.0,0.29.1,0.31.2,0.31.3,0.32.0,0.32.2,0.33.0"
@@ -20,7 +20,6 @@ jobs:
       id-token: write
 
     steps:
-
       - name: Configure AWS credentials
         run: |
           cd $HOME; mkdir ~/.aws; touch ~/.aws/credentials; touch ~/.aws/config
@@ -30,7 +29,7 @@ jobs:
           echo "[default]
           region=auto
           output=json"  > ~/.aws/config
-          
+
       - name: Checkout code
         uses: actions/checkout@v2
         with:
@@ -44,65 +43,56 @@ jobs:
       - name: Create folder structures for Linux
         run: |
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-          mkdir -p ~/linux/axelard_$version-1_amd64/usr/bin/
-          mkdir -p ~/linux/axelard_$version-1_amd64/DEBIAN/
-          mkdir -p ~/linux/axelard_$version-1_arm64/usr/bin/
-          mkdir -p ~/linux/axelard_$version-1_arm64/DEBIAN/
-          mkdir -p ~/linux/axelard_$version-1_arm/usr/bin/
-          mkdir -p ~/linux/axelard_$version-1_arm/DEBIAN/   
-          done 
-          
+            for arch in amd64 arm64 arm; do
+              mkdir -p ~/linux/axelard_$version-1_$arch/usr/bin/
+              mkdir -p ~/linux/axelard_$version-1_$arch/DEBIAN/
+            done
+          done
+
       - name: Get binaries
         run: |
-          architecture_list="amd64,arm64,arm"
-
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-              for arch in $(echo $architecture_list | tr "," "\n"); do
-                  filename="axelard_${version}-1_${arch}.deb"
-
-                  if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
-                      echo "Downloading $filename..."
-                      wget -O ~/linux/axelard_${version}-1_${arch}/usr/bin/axelard --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v${version}/axelard-linux-${arch}-v${version}
-                      chmod 755 ~/linux/axelard_${version}-1_${arch}/usr/bin/axelard
-                  else
-                      echo "Package file already exists in S3: $filename"
-                  fi
-              done
+            for arch in amd64 arm64 arm; do
+              filename="axelard_$version-1_$arch.deb"
+              if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+                echo "Downloading $filename..."
+                wget -O ~/linux/axelard_$version-1_$arch/usr/bin/axelard --no-check-certificate "https://github.com/axelarnetwork/axelar-core/releases/download/v$version/axelard-linux-$arch-v$version"
+                chmod 755 ~/linux/axelard_$version-1_$arch/usr/bin/axelard
+              else
+                echo "Package file already exists in S3: $filename"
+              fi
+            done
           done
 
       - name: Create control files
         continue-on-error: true
         run: |
-          architecture_list="amd64,arm64,arm"
-
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-              for arch in $(echo $architecture_list | tr "," "\n"); do
-                  echo "Package: axelard
-                  Version: $version
-                  Maintainer: axelar <devops@axelar.network>
-                  Architecture: $arch
-                  Homepage: https://axelar.network
-                  Description: axelard binary for Linux $arch" > ~/linux/axelard_${version}-1_${arch}/DEBIAN/control
-              done
+            for arch in amd64 arm64 arm; do
+              echo "Package: axelard
+              Version: $version
+              Maintainer: axelar <devops@axelar.network>
+              Architecture: $arch
+              Homepage: https://axelar.network
+              Description: axelard binary for Linux $arch" \
+              > ~/linux/axelard_$version-1_$arch/DEBIAN/control
+            done
           done
-        
+
       - name: Build the packages if they don't exist on S3
         continue-on-error: true
         run: |
-
-          architecture_list="amd64,arm64,arm"
-
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-              for arch in $(echo $architecture_list | tr "," "\n"); do
-                  filename="axelard_${version}-1_${arch}.deb"
+            for arch in amd64 arm64 arm; do
+              filename="axelard_$version-1_$arch.deb"
 
-                  if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
-                      echo "Package not present in S3: $output"
-                      dpkg --build ~/linux/axelard_${version}-1_${arch}
-                  else
-                      echo "Package file already exists in S3: $filename"
-                  fi
-              done
+              if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+                echo "Package not present in S3: $output"
+                dpkg --build ~/linux/axelard_$version-1_$arch
+              else
+                echo "Package file already exists in S3: $filename"
+              fi
+            done
           done
 
       - name: List files in /home/runner/linux/ directory
@@ -114,50 +104,46 @@ jobs:
       - name: Check the packages
         continue-on-error: true
         run: |
-
-          architecture_list="amd64,arm64,arm"
-
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-              for arch in $(echo $architecture_list | tr "," "\n"); do
-                  file="/home/runner/linux/axelard_${version}-1_${arch}.deb"
-
-                  if [ -f $file ]; then
-                      dpkg-deb --info $file
-                      dpkg-deb --contents $file
-                  fi
-              done
+            for arch in amd64 arm64 arm; do
+              file="/home/runner/linux/axelard_$version-1_$arch.deb"
+              if [ -f $file ]; then
+                dpkg-deb --info $file
+                dpkg-deb --contents $file
+              fi
+            done
           done
 
       - name: Copy binaries in apt repo
         continue-on-error: true
         run: |
           mkdir -p ~/axelard/apt-repo/pool/main/
-            if ls /home/runner/linux/*.deb; then
-              cp /home/runner/linux/*.deb ~/axelard/apt-repo/pool/main/.
-            fi
+          if ls /home/runner/linux/*.deb; then
+            cp /home/runner/linux/*.deb ~/axelard/apt-repo/pool/main/.
+          fi
           ls -l ~/axelard/apt-repo/pool/main/
-          
+
       - name: Generate Packages files
         continue-on-error: true
         run: |
-          architecture_list="amd64,arm64,arm"
+          mkdir -p ~/axelard/apt-repo/dists/stable/main/binary-amd64
+          mkdir -p ~/axelard/apt-repo/dists/stable/main/binary-arm64
+          mkdir -p ~/axelard/apt-repo/dists/stable/main/binary-arm
 
-          mkdir -p ~/axelard/apt-repo
           cd ~/axelard/apt-repo
 
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-              for arch in $(echo $architecture_list | tr "," "\n"); do
-                  mkdir -p dists/stable/main/binary-$arch
+            for arch in amd64 arm64 arm; do
+              if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_${arch}.deb ]; then
+                dpkg-scanpackages -m --arch $arch pool/ > dists/stable/main/binary-${arch}/Packages
+                cat dists/stable/main/binary-${arch}/Packages | gzip -9 > dists/stable/main/binary-${arch}/Packages.gz
+              else
+                echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_${arch}.deb"
+                continue
+              fi
 
-                  if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_${arch}.deb ]; then
-                      dpkg-scanpackages -m --arch $arch pool/ > dists/stable/main/binary-$arch/Packages
-                      cat dists/stable/main/binary-$arch/Packages | gzip -9 > dists/stable/main/binary-$arch/Packages.gz
-                  else
-                      echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_${arch}.deb"
-                  fi
-
-                  cat ~/axelard/apt-repo/dists/stable/main/binary-$arch/Packages
-              done
+              cat ~/axelard/apt-repo/dists/stable/main/binary-${arch}/Packages
+            done
           done
 
       - name: Generate Release file
@@ -234,13 +220,13 @@ jobs:
         run: |
           curl https://keybase.io/axelardev/pgp_keys.asc | gpg --import
           curl https://keybase.io/axelardev/pgp_keys.asc | sudo apt-key add -
- 
+
       - name: Install axelard and test
         continue-on-error: true
         run: |
           echo "deb [arch=amd64] http://static.axelar.network/axelard/apt-repo stable main" | sudo tee /etc/apt/sources.list.d/axelar.list
           sudo apt-get clean
-          sudo apt-get update 
+          sudo apt-get update
           sudo apt list --all-versions axelard
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
             if sudo apt-get install -y axelard=$version; then
@@ -249,4 +235,5 @@ jobs:
               sudo apt-get remove -y axelard=$version
             fi
           done
+
 
