test

diff --git a/.github/workflows/packaging.yaml b/.github/workflows/packaging.yaml
--- a/.github/workflows/packaging.yaml
+++ b/.github/workflows/packaging.yaml
@@ -1,10 +1,10 @@
-name: Package apt binaries
+name: Package linux binaries
 
 env:
   VERSIONS_LIST: "0.10.7,0.13.6,0.14.1,0.17.3,0.18.3,0.19.4,0.21.1,0.24.0,0.26.5,0.28.0,0.29.1,0.31.2,0.31.3,0.32.0,0.32.2,0.33.0"
 
 on:
-  push:
+  workflow_dispatch:
 
 jobs:
   package-binaries:
@@ -20,6 +20,7 @@ jobs:
       id-token: write
 
     steps:
+
       - name: Configure AWS credentials
         run: |
           cd $HOME; mkdir ~/.aws; touch ~/.aws/credentials; touch ~/.aws/config
@@ -29,7 +30,7 @@ jobs:
           echo "[default]
           region=auto
           output=json"  > ~/.aws/config
-
+         
       - name: Checkout code
         uses: actions/checkout@v2
         with:
@@ -43,60 +44,105 @@ jobs:
       - name: Create folder structures for Linux
         run: |
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            for arch in amd64 arm64 arm; do
-              mkdir -p ~/linux/axelard_$version-1_$arch/usr/bin/
-              mkdir -p ~/linux/axelard_$version-1_$arch/DEBIAN/
-            done
+          mkdir -p ~/linux/axelard_$version-1_amd64/usr/bin/
+          mkdir -p ~/linux/axelard_$version-1_amd64/DEBIAN/
+          mkdir -p ~/linux/axelard_$version-1_arm64/usr/bin/
+          mkdir -p ~/linux/axelard_$version-1_arm64/DEBIAN/
+          mkdir -p ~/linux/axelard_$version-1_arm/usr/bin/
+          mkdir -p ~/linux/axelard_$version-1_arm/DEBIAN/  
           done
-
+         
       - name: Get binaries
         run: |
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            for arch in amd64 arm64 arm; do
-              filename="axelard_$version-1_$arch.deb"
-              if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
-                echo "Downloading $filename..."
-                wget -O ~/linux/axelard_$version-1_$arch/usr/bin/axelard --no-check-certificate "https://github.com/axelarnetwork/axelar-core/releases/download/v$version/axelard-linux-$arch-v$version"
-                chmod 755 ~/linux/axelard_$version-1_$arch/usr/bin/axelard
-              else
-                echo "Package file already exists in S3: $filename"
-              fi
-            done
+            filename_amd64="axelard_$version-1_amd64.deb"
+            filename_arm64="axelard_$version-1_arm64.deb"
+            filename_arm="axelard_$version-1_arm.deb"
+     
+            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_amd64" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+              echo "Downloading $filename_amd64..."
+              wget -O ~/linux/axelard_$version-1_amd64/usr/bin/axelard --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v$version/axelard-linux-amd64-v$version
+              chmod 755 ~/linux/axelard_$version-1_amd64/usr/bin/axelard
+            else
+              echo "Package file already exists in S3: $filename_amd64"
+            fi
+     
+            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_arm64" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+              echo "Downloading $filename_arm64..."
+              wget -O ~/linux/axelard_$version-1_arm64/usr/bin/axelard --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v$version/axelard-linux-arm64-v$version
+              chmod 755 ~/linux/axelard_$version-1_arm64/usr/bin/axelard
+            else
+              echo "Package file already exists in S3: $filename_arm64"
+            fi
+     
+            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_arm" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+              echo "Downloading $filename_arm..."
+              wget -O ~/linux/axelard_$version-1_arm/usr/bin/axelard --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v$version/axelard-linux-arm-v$version
+              chmod 755 ~/linux/axelard_$version-1_arm/usr/bin/axelard
+            else
+              echo "Package file already exists in S3: $filename_arm"
+            fi
           done
-
+ 
       - name: Create control files
         continue-on-error: true
         run: |
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            for arch in amd64 arm64 arm; do
-              echo "Package: axelard
-              Version: $version
-              Maintainer: axelar <devops@axelar.network>
-              Architecture: $arch
-              Homepage: https://axelar.network
-              Description: axelard binary for Linux $arch" \
-              > ~/linux/axelard_$version-1_$arch/DEBIAN/control
-            done
+          echo "Package: axelard
+          Version: $version
+          Maintainer: axelar <devops@axelar.network>
+          Architecture: amd64
+          Homepage: https://axelar.network
+          Description: axelard binary for Linux amd64" \
+          > ~/linux/axelard_$version-1_amd64/DEBIAN/control
+          echo "Package: axelard
+          Version: $version
+          Maintainer: axelar <devops@axelar.network>
+          Architecture: arm64
+          Homepage: https://axelar.network
+          Description: axelard binary for Linux arm64" \
+          > ~/linux/axelard_$version-1_arm64/DEBIAN/control
+          echo "Package: axelard
+          Version: $version
+          Maintainer: axelar <devops@axelar.network>
+          Architecture: arm
+          Homepage: https://axelar.network
+          Description: axelard binary for Linux arm" \
+          > ~/linux/axelard_$version-1_arm/DEBIAN/control
           done
-
+         
       - name: Build the packages if they don't exist on S3
         continue-on-error: true
         run: |
-          for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            for arch in amd64 arm64 arm; do
-              filename="axelard_$version-1_$arch.deb"
 
-              if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
-                echo "Package not present in S3: $output"
-                dpkg --build ~/linux/axelard_$version-1_$arch
-              else
-                echo "Package file already exists in S3: $filename"
-              fi
-            done
+          for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
+            filename_amd64="axelard_$version-1_amd64.deb"
+            filename_arm64="axelard_$version-1_arm64.deb"
+            filename_arm="axelard_$version-1_arm.deb"
+
+            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_amd64" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+              echo "Package not present in S3: $output"
+              dpkg --build ~/linux/axelard_$version-1_amd64
+            else
+              echo "Package file already exists in S3: $filename_amd64"
+            fi
+
+            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_arm64" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+              echo "Package not present in S3: $output"
+              dpkg --build ~/linux/axelard_$version-1_arm64
+            else
+              echo "Package file already exists in S3: $filename_arm64"
+            fi
+
+            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_arm" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+              echo "Package not present in S3: $output"
+              dpkg --build ~/linux/axelard_$version-1_arm
+            else
+              echo "Package file already exists in S3: $filename_arm"
+            fi
           done
 
       - name: List files in /home/runner/linux/ directory
-        continue-on-error: true
         run: |
           ls -l /home/runner/linux/
           ls -l /home/runner/linux/*.deb
@@ -104,25 +150,37 @@ jobs:
       - name: Check the packages
         continue-on-error: true
         run: |
+
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            for arch in amd64 arm64 arm; do
-              file="/home/runner/linux/axelard_$version-1_$arch.deb"
-              if [ -f $file ]; then
-                dpkg-deb --info $file
-                dpkg-deb --contents $file
-              fi
-            done
+            file_amd64="/home/runner/linux/axelard_$version-1_amd64.deb"
+            file_arm64="/home/runner/linux/axelard_$version-1_arm64.deb"
+            file_arm="/home/runner/linux/axelard_$version-1_arm.deb"
+ 
+            if [ -f $file_amd64 ]; then
+              dpkg-deb --info $file_amd64
+              dpkg-deb --contents $file_amd64
+            fi
+ 
+            if [ -f $file_arm64 ]; then
+              dpkg-deb --info $file_arm64
+              dpkg-deb --contents $file_arm64
+            fi
+ 
+            if [ -f $file_arm ]; then
+              dpkg-deb --info $file_arm
+              dpkg-deb --contents $file_arm
+            fi
           done
 
       - name: Copy binaries in apt repo
         continue-on-error: true
         run: |
           mkdir -p ~/axelard/apt-repo/pool/main/
-          if ls /home/runner/linux/*.deb; then
-            cp /home/runner/linux/*.deb ~/axelard/apt-repo/pool/main/.
-          fi
+            if ls /home/runner/linux/*.deb; then
+              cp /home/runner/linux/*.deb ~/axelard/apt-repo/pool/main/.
+            fi
           ls -l ~/axelard/apt-repo/pool/main/
-
+         
       - name: Generate Packages files
         continue-on-error: true
         run: |
@@ -133,17 +191,33 @@ jobs:
           cd ~/axelard/apt-repo
 
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            for arch in amd64 arm64 arm; do
-              if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_${arch}.deb ]; then
-                dpkg-scanpackages -m --arch $arch pool/ > dists/stable/main/binary-${arch}/Packages
-                cat dists/stable/main/binary-${arch}/Packages | gzip -9 > dists/stable/main/binary-${arch}/Packages.gz
-              else
-                echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_${arch}.deb"
-                continue
-              fi
+            if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_amd64.deb ]; then
+              dpkg-scanpackages -m --arch amd64 pool/ > dists/stable/main/binary-amd64/Packages
+              cat dists/stable/main/binary-amd64/Packages | gzip -9 > dists/stable/main/binary-amd64/Packages.gz
+            else
+              echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_amd64.deb"
+              continue
+            fi
 
-              cat ~/axelard/apt-repo/dists/stable/main/binary-${arch}/Packages
-            done
+            if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_arm64.deb ]; then
+              dpkg-scanpackages -m --arch arm64 pool/ > dists/stable/main/binary-arm64/Packages
+              cat dists/stable/main/binary-arm64/Packages | gzip -9 > dists/stable/main/binary-arm64/Packages.gz
+            else
+              echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_arm64.deb"
+              continue
+            fi
+
+            if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_arm.deb ]; then
+              dpkg-scanpackages -m --arch arm pool/ > dists/stable/main/binary-arm/Packages
+              cat dists/stable/main/binary-arm/Packages | gzip -9 > dists/stable/main/binary-arm/Packages.gz
+            else
+              echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_arm.deb"
+              continue
+            fi
+
+            cat ~/axelard/apt-repo/dists/stable/main/binary-amd64/Packages
+            cat ~/axelard/apt-repo/dists/stable/main/binary-arm64/Packages
+            cat ~/axelard/apt-repo/dists/stable/main/binary-arm/Packages
           done
 
       - name: Generate Release file
@@ -220,7 +294,7 @@ jobs:
         run: |
           curl https://keybase.io/axelardev/pgp_keys.asc | gpg --import
           curl https://keybase.io/axelardev/pgp_keys.asc | sudo apt-key add -
-
+ 
       - name: Install axelard and test
         continue-on-error: true
         run: |
@@ -235,5 +309,3 @@ jobs:
               sudo apt-get remove -y axelard=$version
             fi
           done
-
-
