test

diff --git a/.github/workflows/packaging.yaml b/.github/workflows/packaging.yaml
--- a/.github/workflows/packaging.yaml
+++ b/.github/workflows/packaging.yaml
@@ -97,61 +97,31 @@ jobs:
         run: |
 
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            filename_amd64="axelard_$version-1_amd64.deb"
-            filename_arm64="axelard_$version-1_arm64.deb"
-            filename_arm="axelard_$version-1_arm.deb"
+            filenames=("axelard_$version-1_amd64.deb" "axelard_$version-1_arm64.deb" "axelard_$version-1_arm.deb")
 
-            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_amd64" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
-              echo "Package not present in S3: $output"
-              dpkg --build ~/linux/axelard_$version-1_amd64
-            else
-              echo "Package file already exists in S3: $filename_amd64"
-            fi
-
-            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_arm64" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
-              echo "Package not present in S3: $output"
-              dpkg --build ~/linux/axelard_$version-1_arm64
-            else
-              echo "Package file already exists in S3: $filename_arm64"
-            fi
-
-            if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename_arm" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
-              echo "Package not present in S3: $output"
-              dpkg --build ~/linux/axelard_$version-1_arm
-            else
-              echo "Package file already exists in S3: $filename_arm"
-            fi
+            for filename in "${filenames[@]}"; do
+              if ! output=$(aws s3 ls "s3://axelar-static/axelard/apt-repo/pool/main/$filename" --endpoint-url ${{ secrets.S3_BIN }} 2>&1); then
+                echo "Package not present in S3: $output"
+                dpkg --build "$HOME/linux/axelard_$version-1_${filename%.*}"
+              else
+                echo "Package file already exists in S3: $filename"
+              fi
+            done
           done
-
-      - name: List files in /home/runner/linux/ directory
-        continue-on-error: true
-        run: |
-          ls -l /home/runner/linux/
-          ls -l /home/runner/linux/*.deb
 
       - name: Check the packages
         continue-on-error: true
         run: |
 
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            file_amd64="/home/runner/linux/axelard_$version-1_amd64.deb"
-            file_arm64="/home/runner/linux/axelard_$version-1_arm64.deb"
-            file_arm="/home/runner/linux/axelard_$version-1_arm.deb"
- 
-            if [ -f $file_amd64 ]; then
-              dpkg-deb --info $file_amd64
-              dpkg-deb --contents $file_amd64
-            fi
- 
-            if [ -f $file_arm64 ]; then
-              dpkg-deb --info $file_arm64
-              dpkg-deb --contents $file_arm64
-            fi
- 
-            if [ -f $file_arm ]; then
-              dpkg-deb --info $file_arm
-              dpkg-deb --contents $file_arm
-            fi
+            file_paths=("/home/runner/linux/axelard_$version-1_amd64.deb" "/home/runner/linux/axelard_$version-1_arm64.deb" "/home/runner/linux/axelard_$version-1_arm.deb")
+
+            for file_path in "${file_paths[@]}"; do
+              if [ -f "$file_path" ]; then
+                dpkg-deb --info "$file_path"
+                dpkg-deb --contents "$file_path"
+              fi
+            done
           done
 
       - name: Copy binaries in apt repo
@@ -173,33 +143,24 @@ jobs:
           cd ~/axelard/apt-repo
 
           for version in $(echo $VERSIONS_LIST | tr "," "\n"); do
-            if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_amd64.deb ]; then
-              dpkg-scanpackages -m --arch amd64 pool/ > dists/stable/main/binary-amd64/Packages
-              cat dists/stable/main/binary-amd64/Packages | gzip -9 > dists/stable/main/binary-amd64/Packages.gz
-            else
-              echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_amd64.deb"
-              continue
-            fi
+            declare -a architectures=("amd64" "arm64" "arm")
 
-            if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_arm64.deb ]; then
-              dpkg-scanpackages -m --arch arm64 pool/ > dists/stable/main/binary-arm64/Packages
-              cat dists/stable/main/binary-arm64/Packages | gzip -9 > dists/stable/main/binary-arm64/Packages.gz
-            else
-              echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_arm64.deb"
-              continue
-            fi
+            for architecture in "${architectures[@]}"; do
+              package_file="~/axelard/apt-repo/pool/main/axelard_${version}-1_${architecture}.deb"
+              package_directory="dists/stable/main/binary-${architecture}"
+              package_packages="${package_directory}/Packages"
+              package_packages_gz="${package_directory}/Packages.gz"
 
-            if [ -f ~/axelard/apt-repo/pool/main/axelard_${version}-1_arm.deb ]; then
-              dpkg-scanpackages -m --arch arm pool/ > dists/stable/main/binary-arm/Packages
-              cat dists/stable/main/binary-arm/Packages | gzip -9 > dists/stable/main/binary-arm/Packages.gz
-            else
-              echo "Package file not found: ~/axelard/apt-repo/pool/main/axelard_${version}-1_arm.deb"
-              continue
-            fi
+              if [ -f "$package_file" ]; then
+                dpkg-scanpackages -m --arch "$architecture" pool/ > "$package_packages"
+                cat "$package_packages" | gzip -9 > "$package_packages_gz"
+              else
+                echo "Package file not found: $package_file"
+                continue
+              fi
 
-            cat ~/axelard/apt-repo/dists/stable/main/binary-amd64/Packages
-            cat ~/axelard/apt-repo/dists/stable/main/binary-arm64/Packages
-            cat ~/axelard/apt-repo/dists/stable/main/binary-arm/Packages
+              cat "$package_packages"
+            done
           done
 
       - name: Generate Release file
